version: '3.2'
services:
  minio:
    image: minio/minio:RELEASE.2020-09-10T22-02-45Z
    container_name: minio
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ACCESS_KEY: myaccesskey
      MINIO_SECRET_KEY: mysecretkey
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-create-bucket:
    image: minio/mc
    container_name: minio_create_bucket
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: myaccesskey
      MINIO_SECRET_KEY: mysecretkey
      MINIO_ENDPOINT: minio:9000
      MINIO_BUCKET: thanos-data-bucket
    volumes:
      - ./data/minio:/data
      - ./create_bucket.sh:/create_bucket.sh
    entrypoint: /create_bucket.sh

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    volumes:
      - ./grafana/provisioning:/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PROVISIONING=/provisioning
    restart: unless-stopped
    ports:
      - "3000:3000"

  thanos_querier:
    build:
      context: ./thanos
      dockerfile: Dockerfile.thanos
    container_name: thanos_querier
    command:
      - "/thanos"
      - "query"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - "--store=thanos_store:10901"
      - "--store=thanos_recieve:10901"
      - "--store.sd-interval=5m"
      - "--query.replica-label=monitor"
    expose:
      - 10902
      - 10901
    ports:
      - "10902:10902"
    depends_on:
      - minio

  thanos_query_frontend:
    build:
      context: ./thanos
      dockerfile: Dockerfile.thanos
    container_name: thanos_query_frontend
    command:
      - "/wait-for-it.sh"
      - "thanos_querier:10901"
      - "--"
      - "/thanos"
      - "query-frontend"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - "--http-address=0.0.0.0:19090"
      - "--query-frontend.compress-responses"
      - "--query-range.partial-response"
      - "--query-frontend.downstream-url=http://thanos_querier:10902"
      - "--query-range.split-interval=24h"
      - "--query-range.max-retries-per-request=5"
      - "--query-frontend.log-queries-longer-than=5s"
      - "--cache-compression-type=snappy"
    ports:
      - "19090:19090"
    depends_on:
      - thanos_querier

  thanos_compactor:
    build:
      context: ./thanos
      dockerfile: Dockerfile.thanos
    container_name: thanos_compactor
    command:
      - "/wait-for-it.sh"
      - "minio:9000"
      - "--"
      - "/thanos"
      - "compact"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - |
        --objstore.config=type: S3
        config: 
            bucket: thanos-data-bucket
            access_key: myaccesskey
            secret_key: mysecretkey
            endpoint: minio:9000
            insecure: true
      - "--data-dir=/data"
      - "--consistency-delay=30m"
      - "--retention.resolution-raw=30d"
      - "--retention.resolution-5m=120d"
      - "--retention.resolution-1h=1y"
      - "--compact.concurrency=1"
      - "--delete-delay=15m"
      - "--wait"
      - "--wait-interval=3m"
      - "--compact.enable-vertical-compaction"
    expose:
      - 10902
      - 10901
    ports:
      - "10922:10902"
    depends_on:
      - minio

  thanos_store:
    build:
      context: ./thanos
      dockerfile: Dockerfile.thanos
    container_name: thanos_store
    command:
      - "/wait-for-it.sh"
      - "minio:9000"
      - "--"
      - "/thanos"
      - "store"
      - "--log.level=debug"
      - |
        --objstore.config=type: S3
        config: 
            bucket: thanos-data-bucket
            access_key: myaccesskey
            secret_key: mysecretkey
            endpoint: minio:9000
            insecure: true
      - "--data-dir=/data"
      - "--log.format=logfmt"
      - "--index-cache-size=250MB"
      - "--chunk-pool-size=1GB"
      - "--store.grpc.series-max-concurrency=20"
      - "--sync-block-duration=3m"
      - "--block-sync-concurrency=20"
    restart: unless-stopped
    expose:
      - 10902
      - 10901
    depends_on:
      - minio
    ports:
      - '10912:10902'

  thanos_recieve:
    build:
      context: ./thanos
      dockerfile: Dockerfile.thanos
    container_name: thanos_recieve
    volumes:
      - ./data/store:/data
    command:
      - "/wait-for-it.sh"
      - "minio:9000"
      - "--"
      - "/thanos"
      - "receive"
      - '--label=recive="1"'
      - "--log.level=debug"
      - |
        --objstore.config=type: S3
        config:
            bucket: thanos-data-bucket
            access_key: myaccesskey
            secret_key: mysecretkey
            endpoint: minio:9000
            insecure: true
      - "--tsdb.path=/data"
      - "--log.format=logfmt"
      - "--tsdb.out-of-order.time-window=1y"
    restart: unless-stopped
    expose:
      - 10902
      - 10901
    depends_on:
      - minio
    ports:
      - '10932:10902'
      - '19291:19291'
